import * as FileSystem from "expo-file-system";

const DOCUMENTS_DIR = (FileSystem as any).documentDirectory || "";

// Fallback for share functionality
const Sharing = {
  isAvailableAsync: async () => false,
  shareAsync: async () => ({}),
};

/**
 * Generate simple PDF content (HTML to send to printer/share)
 * In production, use: expo-pdf or similar for true PDF generation
 */
export interface PDFContent {
  title: string;
  content: string;
  subject?: string;
  grade?: string;
  generatedAt?: string;
}

/**
 * Convert markdown to HTML for PDF
 */
function convertMarkdownToHTML(markdown: string): string {
  let html = markdown
    .replace(/^## (.*?)$/gm, "<h2>$1</h2>")
    .replace(/^### (.*?)$/gm, "<h3>$1</h3>")
    .replace(/^# (.*?)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^- (.*?)$/gm, "<li>$1</li>")
    .replace(/(<li>.*?<\/li>)/s, "<ul>$1</ul>")
    .replace(/\n/g, "<br>");

  return html;
}

/**
 * Generate HTML content for PDF
 */
function generateHTMLContent(pdfContent: PDFContent): string {
  const contentHTML = convertMarkdownToHTML(pdfContent.content);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${pdfContent.title}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      margin: 40px;
      background: white;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
    }
    h2 {
      color: #34495e;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    h3 {
      color: #7f8c8d;
    }
    strong {
      color: #c0392b;
      font-weight: bold;
    }
    ul {
      margin: 10px 0;
      padding-left: 30px;
    }
    .metadata {
      background: #ecf0f1;
      padding: 10px;
      border-radius: 5px;
      margin-bottom: 20px;
      font-size: 12px;
    }
    .footer {
      margin-top: 40px;
      border-top: 1px solid #bdc3c7;
      padding-top: 10px;
      font-size: 11px;
      color: #7f8c8d;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${pdfContent.title}</h1>
  
  <div class="metadata">
    ${pdfContent.subject ? `<div><strong>Subject:</strong> ${pdfContent.subject}</div>` : ""}
    ${pdfContent.grade ? `<div><strong>Grade:</strong> ${pdfContent.grade}</div>` : ""}
    ${pdfContent.generatedAt ? `<div><strong>Generated:</strong> ${pdfContent.generatedAt}</div>` : ""}
  </div>

  <div class="content">
    ${contentHTML}
  </div>

  <div class="footer">
    Generated by LearnovaX - Your AI-powered study companion
    <br>
    ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `;
}

export async function exportAsPDF(pdfContent: PDFContent): Promise<boolean> {
  try {
    const htmlContent = generateHTMLContent(pdfContent);
    const filename = `${pdfContent.title.replace(/\s+/g, "_")}_${Date.now()}.html`;
    const fileUri = `${DOCUMENTS_DIR}${filename}`;
    await FileSystem.writeAsStringAsync(fileUri, htmlContent);
    console.log("PDF exported:", fileUri);
    return true;
  } catch (error) {
    console.error("Failed to export PDF:", error);
    return false;
  }
}

/**
 * Generate CSV export for exam results
 */
export async function exportAsCSV(
  data: {
    question: string;
    userAnswer: string;
    correctAnswer: string;
    score: number;
    maxScore: number;
  }[],
  filename: string
): Promise<boolean> {
  try {
    // Generate CSV content
    const headers = ["Question", "Your Answer", "Correct Answer", "Score", "Max Score"];
    const rows = data.map((item) => [
      `"${item.question.replace(/"/g, '""')}"`,
      `"${item.userAnswer.replace(/"/g, '""')}"`,
      `"${item.correctAnswer.replace(/"/g, '""')}"`,
      item.score,
      item.maxScore,
    ]);

    const csvContent = [
      headers.join(","),
      ...rows.map((row) => row.join(",")),
    ].join("\n");

    // Write to file
    const csvFilename = `${filename.replace(/\s+/g, "_")}_${Date.now()}.csv`;
    const fileUri = `${DOCUMENTS_DIR}${csvFilename}`;
    await FileSystem.writeAsStringAsync(fileUri, csvContent);

    // Share (stub - would share in production)
    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      console.log("Would share:", fileUri);
      return true;
    }
    return false;
  } catch (error) {
    console.error("Failed to export CSV:", error);
    return false;
  }
}

export async function saveToLocalFile(content: string, filename: string, subfolder = "LearnovaX"): Promise<string | null> {
  try {
    const dirUri = `${DOCUMENTS_DIR}${subfolder}/`;
    try {
      await FileSystem.getInfoAsync(dirUri);
    } catch {
      await FileSystem.makeDirectoryAsync(dirUri, { intermediates: true });
    }
    const fileUri = `${dirUri}${filename.replace(/\s+/g, "_")}_${Date.now()}.txt`;
    await FileSystem.writeAsStringAsync(fileUri, content);
    return fileUri;
  } catch (error) {
    console.error("Failed to save file:", error);
    return null;
  }
}

/**
 * Load content from local file
 */
export async function loadFromLocalFile(fileUri: string): Promise<string | null> {
  try {
    const content = await FileSystem.readAsStringAsync(fileUri);
    return content;
  } catch (error) {
    console.error("Failed to load file:", error);
    return null;
  }
}

/**
 * List all saved files
 */
export async function listSavedFiles(subfolder = "LearnovaX"): Promise<string[]> {
  try {
    const dirUri = `${DOCUMENTS_DIR}${subfolder}/`;
    const files = await FileSystem.readDirectoryAsync(dirUri);
    return files.filter((file) => !file.startsWith("."));
  } catch (error) {
    console.warn("Failed to list files:", error);
    return [];
  }
}

/**
 * Delete a saved file
 */
export async function deleteSavedFile(fileUri: string): Promise<boolean> {
  try {
    await FileSystem.deleteAsync(fileUri);
    return true;
  } catch (error) {
    console.error("Failed to delete file:", error);
    return false;
  }
}

/**
 * Get file size
 */
export async function getFileSize(fileUri: string): Promise<number | null> {
  try {
    const fileInfo = await FileSystem.getInfoAsync(fileUri);
    if (fileInfo.exists && "size" in fileInfo) {
      return (fileInfo as any).size || null;
    }
    return null;
  } catch (error) {
    console.error("Failed to get file size:", error);
    return null;
  }
}

/**
 * Clear all saved files
 */
export async function clearAllSavedFiles(subfolder = "LearnovaX"): Promise<void> {
  try {
    const files = await listSavedFiles(subfolder);
    const dirUri = `${DOCUMENTS_DIR}${subfolder}/`;
    for (const file of files) {
      await FileSystem.deleteAsync(`${dirUri}${file}`);
    }
  } catch (error) {
    console.error("Failed to clear files:", error);
  }
}
